- name: Update inventory
  hosts: libvirt
  connection: local
  become: yes
  gather_facts: no
  tasks:
	- name: Add VMs to AAP inventory
  	  tower_host:
    	    name: "{{ inventory_hostname }}"
    	    inventory: "RHEL KVM Host"
    	    variables:
      	      ansible_host: "{{ansible_host}}"
      	      ansible_become: yes
      	      ansible_become_method: enable
